site_name: æ—¥æœ¬èªå­¦ä¹ ç¬”è®° ğŸ‡¯ğŸ‡µ
site_description: Tony Chang çš„æ—¥æœ¬èªå­¦ä¹ ç¬”è®°
site_author: Tony Chang
copyright: Copyright Â© 2012-2022 Tong Chang. All Right Reserved.
site_url: http://jln.aptx4869.tv
theme:
  name: material
  # language: zh
  palette:
    primary: blue
repo_name: GitHub
repo_url: https://github.com/tony-aptx4869/jln_mkdocs_for_rtd
edit_uri: blob/main/docs/

# Navigation
nav:
  # Default Language (zh, Simplified Chinese, ç®€ä½“ä¸­æ–‡)
  - home_navi_title: index.md
  - about_nav_title: about.md
  # zh-TW, Traditional Chinese(Taiwan, China), æ­£é«”ä¸­æ–‡
  - home_navi_title: index.zh-TW.md
  - about_nav_title: about.zh-TW.md
  # English
  - home_navi_title: index.en.md
  - about_nav_title: about.en.md

# mkdocs-i18n
plugins:
  - search
  - i18n:
      languages:
        zh: "ç®€ä½“ä¸­æ–‡"
        zh-TW: "æ­£é«”ä¸­æ–‡"
        en: "English"
      # default_language: 'en'
      default_language: 'zh'
      # no_translation:
      #   zh: "æ­¤é¡µé¢å°šæœªç¿»è¯‘æˆç®€ä½“ä¸­æ–‡ç‰ˆæœ¬ã€‚"
      #   zh-TW: "è©²é é¢å°šæœªç¿»è­¯çˆ²æ­£é«”ä¸­æ–‡ç‰ˆæœ¬ã€‚"
      #   en: "This page isn't translated to English."
      translate_nav:
        zh:
          home_navi_title: "é¦–é¡µ"
          about_nav_title: "å…³äº"
        zh-TW:
          home_navi_title: "é¦–é "
          about_nav_title: "é—œæ–¼"
        en:
          home_navi_title: "Home"
          about_nav_title: "About"

# Language Switcher
extra:
  alternate:
    - name: ç®€ä½“ä¸­æ–‡
      lang: zh
    - name: æ­£é«”ä¸­æ–‡
      lang: zh-TW
    - name: English
      lang: en
